// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bottom-sheet/AuroraMesh.tsx": () => import("../components/mockups/bottom-sheet/AuroraMesh.tsx"),
  "./components/mockups/bottom-sheet/Glassmorphic.tsx": () => import("../components/mockups/bottom-sheet/Glassmorphic.tsx"),
  "./components/mockups/bottom-sheet/SolidDark.tsx": () => import("../components/mockups/bottom-sheet/SolidDark.tsx")
};
